### ISSUE TITLE
Getting this module up-to-date with the Drupal version

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/imce#15]
This module hasn't been updated in years.

Lots of things happened on Drupal side in the meantime. High time to get things in sync again, I guess: https://www.drupal.org/project/imce

@docwilmot you've been involved in porting this module, but aren't an official maintainer. In fact, this module appears sort of unmaintained. Are you interested in coordinating updates here, or do we have to rely on the @backdrop-contrib/bug-squad?

Assuming, this module's based on 7.x-1.x, here's a list of commits:
https://git.drupalcode.org/project/imce/-/commits/7.x-1.x

Probably not all are relevant for Backdrop, but some still are. Note that there has also been some merge-revert re some issues.

- [ ] #xx | [fc5a5e5](https://git.drupalcode.org/project/imce/-/commit/fc5a5e55235f3ff382889b631fe417ef0ce5aba7) | [#2268585, #2279539: Consider subdirectories array might be altered by other modules.](https://drupal.org/node/)
- [ ] #xx | [722345e](https://git.drupalcode.org/project/imce/-/commit/722345e4c747e9579548442247b6f3d3e30d7536) | [Fixed typos.](https://drupal.org/node/)
- [ ] #xx | [8c6f29d](https://git.drupalcode.org/project/imce/-/commit/8c6f29dde7c1d38844f2972fcf458cc91bff3251) | [Issue #2517684 by rrfegade: Spelling errors](https://drupal.org/node/)
- [ ] #xx | [62c0c81](https://git.drupalcode.org/project/imce/-/commit/62c0c8194fa97e623cc1ca5cd883c964b1c4df6a) | [Added ability to return uncached urls by getURL(). Made preview image url an uncached url.](https://drupal.org/node/)
- [ ] #xx | [52dfd14](https://git.drupalcode.org/project/imce/-/commit/52dfd14957cdb879b034d73e5978f8201b2fcd6a) | [Added 'file_stream_wrapper_uri_normalize' altering to imce_dir_uri() as per #2530388.](https://drupal.org/node/)
- [ ] #xx | [b7d6f5a](https://git.drupalcode.org/project/imce/-/commit/b7d6f5a85a04ea3e481fe30d4dbf16e7518c4946) | [Removed attr() usage for disabling submit button.](https://drupal.org/node/)
- [ ] #23 | [0b60beb](https://git.drupalcode.org/project/imce/-/commit/0b60beb560e986ff6b03ebea64db072bb6ff6ae2) | [Issue #2696609 by a.mamallan: Replaced basename() with drupal_basename() for unicode support.](https://www.drupal.org/project/imce/issues/2696609)
- [ ] #xx | [390aff0](https://git.drupalcode.org/project/imce/-/commit/390aff038ada0c94ff77370e7732fe24d55b44bd) | [Issue #2863312 by michael.krainiuk: Fixed port number in file URLs](https://drupal.org/node/)
- [ ] #xx | [8786b63](https://git.drupalcode.org/project/imce/-/commit/8786b63587be86ccec11e7ada1d68b44986b1802) | [Issue #2357871 by Timo Vogt, DamienMcKenna: Permit IMCE to use the Administration Theme](https://drupal.org/node/)
- [ ] #xx | [5bea0b2](https://git.drupalcode.org/project/imce/-/commit/5bea0b20eac8f816609a0d70b19c9219953d273c) | [Issue #2891824 by apokryfos: Fixed subdirs iteration.](https://drupal.org/node/)
- [ ] #xx | [9399663](https://git.drupalcode.org/project/imce/-/commit/93996633b2b3302f5291efe7e799f223f5124ffd) | [Close imceInline popup to fix the focus issues after file insertion.](https://drupal.org/node/)
- [x] #24 | [d4ab9f1](https://git.drupalcode.org/project/imce/-/commit/d4ab9f14cb4eb82ceacaf6f23a1a0c79f4a6cc62) | [Issue #126679 by emmonsaz, thalles, alimc29, joelpittet, hanief84, ufku, dalin: Bulk Upload Ability](https://www.drupal.org/project/imce/issues/126679)
- [ ] #xx | [53fac0c](https://git.drupalcode.org/project/imce/-/commit/53fac0c345107bedb9a010361437b45db3d3b69e) | [Issue #3061047 by thalles: Clear code on inc/imce.page.inc](https://drupal.org/node/)
- [ ] #xx | [831fcbc](https://git.drupalcode.org/project/imce/-/commit/831fcbc61a10db82e27becbe90610bdbe78481aa) | [Issue #3061307 by thalles: Clear code on inc/imce.core.profiles.inc](https://drupal.org/node/)
- [ ] #xx | [ea17846](https://git.drupalcode.org/project/imce/-/commit/ea178468fb7acb753dadd94a9c5dc67feb2d0530) | [Issue #3061316 by thalles: Refactor code on inc/imce.js.inc](https://drupal.org/node/)
- [ ] #xx | [1248d7a](https://git.drupalcode.org/project/imce/-/commit/1248d7a53c8edd0db9e88baa6a643954dba06bf3) | [Issue #3061328 by thalles: Rename README.txt to README.md](https://drupal.org/node/)
- [ ] #xx | [48884ae](https://git.drupalcode.org/project/imce/-/commit/48884aecfefa2c07f3ce2ea0690d4fac2486e753) | [Issue #3062358 by thalles: Refactor code on imce.module](https://drupal.org/node/)
- [ ] #xx | [20657a5](https://git.drupalcode.org/project/imce/-/commit/20657a5d5c306366d963f799a5c9083013754ebd) | [Issue #3062528 by thalles: Clear code on inc/imce.admin.inc](https://drupal.org/node/)
- [ ] #xx | [510821d](https://git.drupalcode.org/project/imce/-/commit/510821d5100689ee41cdc57778db08e031ef753e) | [Issue #3062569 by thalles: Clear code on template file of IMCE](https://drupal.org/node/)
- [ ] #xx | [e6ba7d3](https://git.drupalcode.org/project/imce/-/commit/e6ba7d3b47c3655d27db826a8f75f8372764b984) | [Issue #3126456 by thalles: Fix some erro in README.md](https://drupal.org/node/)
- [ ] #xx | [84a5d6a](https://git.drupalcode.org/project/imce/-/commit/84a5d6a3d00e0c657dd4fe0d44103ba9efdacd77) | [Issue #3126456 by thalles: Fix some erro in README.md](https://drupal.org/node/)
- [ ] #xx | [a5297c2](https://git.drupalcode.org/project/imce/-/commit/a5297c23c3f0ba747631f6078a102c9fe84fed21) | [Issue #3126473 by thalles: Do not concatenate strings to translatable strings](https://drupal.org/node/)
- [ ] #xx | [41ab1c4](https://git.drupalcode.org/project/imce/-/commit/41ab1c480db3798b3c44ed910456cd0c8fe0e2ec) | [Issue #3126477 by thalles: Add maintainers list in README.md](https://drupal.org/node/)
- [x] #22 | [4b9fc5d](https://git.drupalcode.org/project/imce/-/commit/4b9fc5d02b4a28ce86b550ea4f847950f18e21ed) | [Issue #1673764 by DamienMcKenna: 508 Keyboard Accessibility](https://www.drupal.org/project/imce/issues/1673764)
- [ ] #xx | [311c37f](https://git.drupalcode.org/project/imce/-/commit/311c37f19e3613a467df8e17a2d202f7d185f076) | [Revert "Issue #1673764 by DamienMcKenna: 508 Keyboard Accessibility"](https://www.drupal.org/)
- [ ] #xx | [417f87e](https://git.drupalcode.org/project/imce/-/commit/417f87e0defeeb78656327c2a99442064061dbe2) | [Issue #2174847 by bkonetzny: Better preview for images with transparency or white images](https://drupal.org/node/)
- [ ] #xx | [aa79038](https://git.drupalcode.org/project/imce/-/commit/aa790380fb0f5a18bedf4c99078ebf00f691df23) | [Issue #2231251 by nico.knaepen, paulocs, Suresh Prabhu Parkala: Let the user decide wich action to apply on uploading](https://drupal.org/node/)
- [ ] #xx | [ef11aed](https://git.drupalcode.org/project/imce/-/commit/ef11aed3bad7801e5d36665dc923ef9a5342c5f0) | [Issue #1673764 by DamienMcKenna, paulocs, thalles: 508 Keyboard Accessibility](https://drupal.org/node/)
- [ ] #xx | [dad5734](https://git.drupalcode.org/project/imce/-/commit/dad5734a5f0d76949c6eb0020d7c30196f06e405) | [Issue #1437704 by paulocs, mesr01, thalles: A general place for IMCE in the admin area?](https://drupal.org/node/)
- [ ] #xx | [75cd13c](https://git.drupalcode.org/project/imce/-/commit/75cd13ca0adb04e6e8debe0ed830d4c09ccd8e6d) | [Issue #3005180 by snowl, thalles: Operation Tabs Error "You can not perform this operation" when working with HTML5 Themes](https://drupal.org/node/)
- [ ] #xx | [98f66b2](https://git.drupalcode.org/project/imce/-/commit/98f66b27a8ddb32523b1a87c6a580d32da28cfa1) | [Issue #2976669 by paulocs, thalles: Show a "download" button in file browser line items](https://drupal.org/node/)
- [ ] #xx | [cdf7169](https://git.drupalcode.org/project/imce/-/commit/cdf7169020dcd82c063f001a83cd8b2d26305bf0) | [Issue #3084709 by socketwench, paulocs, thalles: Add disable switch for image metadata fetch](https://drupal.org/node/)
- [ ] #xx | [68acb99](https://git.drupalcode.org/project/imce/-/commit/68acb99dfcf658c7247d495b0118ede3212b03d3) | [Issue #3151874 by DamienMcKenna, paulocs: Skip the lost+found directory on UNIX systems](https://drupal.org/node/)
- [ ] #xx | [4b5757f](https://git.drupalcode.org/project/imce/-/commit/4b5757fe14a96c6dc18742aa78d6de93203d831b) | [Issue #3151873 by paulocs, DamienMcKenna: Use APC cache for imce_image_info()](https://drupal.org/node/)
- [ ] #xx | [6291927](https://git.drupalcode.org/project/imce/-/commit/62919273964ea4d78235959d3460bf92ee28930f) | [Revert "Issue #3084709 by socketwench, paulocs, thalles: Add disable switch for image metadata fetch"](https://drupal.org/node/)
- [ ] #xx | [a3baa0b](https://git.drupalcode.org/project/imce/-/commit/a3baa0b54eb25566822a4df8445eaca05fb7e848) | [Issue #3152137 by thalles: Feature resize don't works](https://drupal.org/node/)
- [ ] #xx | [4120fad](https://git.drupalcode.org/project/imce/-/commit/4120fade2a68884146723a705b4656a81a512903) | [Issue #1594434 by thalles, Kingdutch: Improve file select feedback](https://drupal.org/node/)
- [ ] #xx | [639000c](https://git.drupalcode.org/project/imce/-/commit/639000cf190a158d535431e82a8184171913f71d) | [Issue #3152671 by thalles: Image don't load](https://drupal.org/node/)
- [ ] #xx | [ae0d91c](https://git.drupalcode.org/project/imce/-/commit/ae0d91ca78c6b2b3272ccb578613e26ea13fb57a) | [Issue #3084709 by paulocs, socketwench, thalles: Add disable switch for image metadata fetch](https://drupal.org/node/)
- [ ] #xx | [44b6d7f](https://git.drupalcode.org/project/imce/-/commit/44b6d7fd2ed9a07ab0d6c113e8c03e34ec006e37) | [Issue #2886433 by paulocs: Setting of initial sorting column](https://drupal.org/node/)
- [ ] #xx | [6d4362d](https://git.drupalcode.org/project/imce/-/commit/6d4362db93439f30d0e2767b865857c9ee0312f1) | [Issue #3024769 by paulocs, geoffmen, thalles: Column widths issues](https://drupal.org/node/)
- [ ] #xx | [c720168](https://git.drupalcode.org/project/imce/-/commit/c720168a6148bd8eaadad4377813233994ff295d) | [Issue #1050244 by lee20, cajinx, irritare: File tools don't appear after upgrade](https://drupal.org/node/)
- [ ] #xx | [2d17651](https://git.drupalcode.org/project/imce/-/commit/2d17651e226264c6eec48ae5b34345564e3438af) | [Issue #1804062 by thalles, prakashsingh: Validation required](https://drupal.org/node/)
- [ ] #xx | [df9c927](https://git.drupalcode.org/project/imce/-/commit/df9c9277a426514f8535dc272dcaedb8ece96462) | [Issue #3302806: Fixed warnings caused by SA-CORE-2022-012](https://drupal.org/node/)
- [ ] #xx | [6bbda6f](https://git.drupalcode.org/project/imce/-/commit/6bbda6f2ff8dbaeefc1a046410e91c56d069a73d) | [Revert "Issue #1804062 by thalles, prakashsingh: Validation required"](https://drupal.org/node/)

Generated with `git log 7.x-1.9..HEAD --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://git.drupalcode.org/project/imce/-/commit/%H) | [%s](https://drupal.org/node/)"`. The links to D-org issues have to get added manually.

**Comment by indigoxela** [comment]
The Backdrop stats list 274 installs of this module - not huge, but still relevant.
